"""initial schema

Revision ID: 7f440a49f3a9
Revises:
Create Date: 2026-10-07 17:09:35.258780

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "7f440a49f3a9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_companies_name_lower", "companies", [sa.literal_column("lower(name)")], unique=True
    )
    op.create_table(
        "applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.String(length=300), nullable=False),
        sa.Column("job_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "ATS", "REFERRAL", "LINKEDIN", "COMPANY_SITE", "OTHER", name="application_source"
            ),
            nullable=False,
        ),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("remote", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "APPLIED",
                "OA",
                "INTERVIEWING",
                "OFFER",
                "ACCEPTED",
                "REJECTED",
                "GHOSTED",
                "WITHDRAWN",
                name="application_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "next_action",
            sa.Enum(
                "FOLLOW_UP",
                "WAITING",
                "PREPARE_OA",
                "PREPARE_INTERVIEW",
                "SEND_EMAIL",
                "DECIDE",
                "NONE",
                name="next_action",
            ),
            nullable=False,
        ),
        sa.Column("applied_at", sa.Date(), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=True),
        sa.Column("message_id", sa.String(length=255), nullable=False),
        sa.Column("sender", sa.String(length=500), nullable=False),
        sa.Column("subject", sa.String(length=1000), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "classification",
            sa.Enum(
                "REJECTION",
                "OA_INVITE",
                "INTERVIEW_INVITE",
                "OFFER",
                "CONFIRMATION",
                "OTHER",
                name="email_classification",
            ),
            nullable=True,
        ),
        sa.Column("confidence", sa.Double(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id"),
    )
    op.create_table(
        "status_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("email_id", sa.Integer(), nullable=True),
        sa.Column(
            "from_status",
            sa.Enum(
                "APPLIED",
                "OA",
                "INTERVIEWING",
                "OFFER",
                "ACCEPTED",
                "REJECTED",
                "GHOSTED",
                "WITHDRAWN",
                name="application_status",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "APPLIED",
                "OA",
                "INTERVIEWING",
                "OFFER",
                "ACCEPTED",
                "REJECTED",
                "GHOSTED",
                "WITHDRAWN",
                name="application_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "source", sa.Enum("MANUAL", "EMAIL", "SYSTEM", name="event_source"), nullable=False
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["email_id"], ["emails.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("status_events")
    op.drop_table("emails")
    op.drop_table("applications")
    op.drop_index("uq_companies_name_lower", table_name="companies")
    op.drop_table("companies")
    op.execute("DROP TYPE application_status")
    op.execute("DROP TYPE application_source")
    op.execute("DROP TYPE next_action")
    op.execute("DROP TYPE email_classification")
    op.execute("DROP TYPE event_source")
    # ### end Alembic commands ###
